### ISSUE TITLE
Can we modify "pre-assigned source of face" from SD to other extension's output?

### ISSUE THREAD

**Issue by nopputta** [ototadana/sd-face-editor#106]
I used A1111 V1.4 and enabled 2 extensions sd-face-editor and sd-roop to work together. I expected sd-face-editor to improve swapped faces from sd-roop but the sequence was not what I expected. Sd-face-editor detected faces from SD directly not the faces from sd-roop. I guessed it was about "pre-assigned source of face" of the extension itself. 

Can we modify "pre-assigned source of face" from SD to other extension's output?

**Comment by ototadana** [comment]
Thanks for using this extension.

Sorry, I didn't understand what "pre-assigned source of face" meant, but I checked three different ways to see if it would work as expected.

1. Source code
I checked https://github.com/s0md3v/sd-webui-roop/blob/main/scripts/faceswap.py and found that the implemented functions are `process`, `postprocess_batch`, `postprocess_ image`. Since these functions run before `postprocess` implemented by Face Editor, I confirmed that the order of execution is (1) sd-roop, (2) Face Editor.

2. Console
The order of the logs displayed on the console when actually running the program was also confirmed to be (1) sd-roop, (2) Face Editor.

3. "Show original image" option
If "Show original image" is enabled in the Face Editor, you can see which image is processed by the Face Editor. It was confirmed that this image was also processed by sd-roop.

So, it appears that the behavior is as expected. However, since Face Editor changes the face significantly, it may not be compatible with the intended use of software like sd-roop.

**Comment by nopputta** [comment]
Oh, thanks so much for your testing and explanation. Anyway, your extension is very useful. :)
