### ISSUE TITLE
It is difficult to restore lora features on the face

### ISSUE THREAD

**Issue by k52252467** [ototadana/sd-face-editor#125]
Hello,
 I think your work is great,
 Your plugin is very efficient,
 Face detection is also very good,
 Of course when the face is tilted,
 poor repair ability,

 But its present repaired face,
 It is difficult to restore lora's facial features,

 I also used other repair software for comparison,
 For example adetailer,
 It can restore the characteristics of lora very well,
 Can you try to do this?
 Even if I increase the weight of lora to 1.5,
 It is also difficult to restore the characteristics of lora,
 The faces it generates seem to have fixed beautification effects,
 It seems to have a lora effect,
 Instead of what I want to emphasize,
 Maybe I didn't express clearly enough,

 You might be able to try adetailer,
 You can understand what I want to express,
 It can restore lora's facial features very well,
 It is hoped that this capacity can be increased

**Comment by ototadana** [comment]
@k52252467 

Sorry.  I tried to follow your advice, but could not find out about a clear difference and its cause. This is probably due to my lack of understanding of lora and my lack of technical skills.

As you said, there were some images that made me think that this software might have more of a beautification effect than a lora effect.

However, it may be rather good news for you. Because you can use other software when you want lora effects and use this software when you want beautification effects.

In any case, thank you so much for trying this extension :heavy_heart_exclamation:

**Comment by k52252467** [comment]
Thank you very much for your answer
