### ISSUE TITLE
Face-Editor criples X/Y/Z Legend grid

### ISSUE THREAD

**Issue by Confuzu** [ototadana/sd-face-editor#135]
At first  i  thought its a automatic bug its not please look at the my open issue at SD  where i  describe it in detail. 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11906

The legend grid contains only the first images when Editor is Enabled 
when Face Editor is disabled it works like it should

**Comment by ototadana** [comment]
I took some time to investigate because I reproduced it in my environment.

If the "Show original image" option is enabled, the image is displayed as expected. 
(However, it is the image before the Face Editor made the changes. I believe it would be quite difficult to get the modified image to display as expected)

**Comment by ototadana** [comment]
I went to sleep and woke up and came up with a way to handle this and will try to implement it later.

**Comment by ototadana** [comment]
@Confuzu 

Done!

If "Show original image" is enabled, the image before modification is displayed; if disabled, the image after modification is displayed.

Please try it.

**Comment by Confuzu** [comment]
The update works great,  the Bug is gone 
Thanks for the fast Response and bug killing
