### ISSUE TITLE
[bug?]why i stunned in total progress and no face edited?

### ISSUE THREAD

**Issue by mlwei1** [ototadana/sd-face-editor#31]
![image](https://user-images.githubusercontent.com/13741913/232751398-7449ecbf-a785-4a27-9e32-409569a62152.png)

**Comment by mlwei1** [comment]
its  end status

**Comment by mlwei1** [comment]
3 girl wear space suits eat box Lunch in 711 convenience stores,masterpiece,8k,light tracing,
Negative prompt: low quality,nsfw,worst quality
Steps: 25, Sampler: Euler a, CFG scale: 7, Seed: 1588529913, Face restoration: CodeFormer, Size: 512x512, Model hash: 812cd9f9d9, Model: anythingV3_fp16

Time taken: 3.77sTorch active/reserved: 3162/3214 MiB, Sys VRAM: 5480/16376 MiB (33.46%)

**Comment by ototadana** [comment]
@mlwei1 
Thanks for trying this script.

I have tried to do the same using the information you provided.
It appears that the faces are not detected.

This script is not good at detecting anime faces. In particular, the faces of the girls in this image appear to be quite difficult to detect because they have almost no noses and mouths.

But even without this script, I think their faces are very kawaii :smiley:

**Comment by creepysnake** [comment]
In my case, The 512x512 has been gen, inpaint the face part is done
however the crop part is not "finished", the final product is a whole 512x512 "face edit image" into the inpaint (face) part.
even the output has 5 steps (512x512, crop face, paste into the original part, actual crop, final product)

also, the whole step indicates the process is not finished. 
number of faces: 1
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.62it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.23it/s]
Total progress:  65%|███████████████████████████████████████████▏                      | 17/26 [00:08<00:04,  2.01it/s]
