### ISSUE TITLE
WE NEED extension version for video frame swap face.

### ISSUE THREAD

**Issue by dundund** [ototadana/sd-face-editor#45]
one extension named batch face swap can do this,
but it is not fast than face editor script,
I am not a developer, I try  change this script to extension,
but failed,
it have return  scripts.AlwaysVisible  ,
the script don't working,
I  don't know how to change code next step,
I kown scripts dropdown must be selected,this script run() then working,
I can't find extensions developing doc, how to use a script as extension.

**Comment by figurehunt** [comment]
i agree with this suggestion. but i will recommend to make it like addional network or controlnet panel just in the middle of the UI, so that i can use more different functions together. 
because sometime I wanted to use another script, but i found i was just using the face editor script. it ocupied.

**Comment by ototadana** [comment]
@dundund 
Thanks for the suggestion.
However, I honestly do not understand the benefit of changing this script to an extension.
Can you please be as specific as possible about the use cases that would be possible by changing this script to an extension?

**Comment by figurehunt** [comment]
@ototadana As for me, sometimes I want to find a new face in different checkpoints or in different LoRAs. I have to test one by one on the current setting, cause the face editor occupied the only one enabled script.
What if the face editor be an additonal panel in the middle of the webui, then I can open up a XYZ script, putting a bunch of checkpoints. after a while, I can check and conpare them alltogether, and find the best one soon. That will be cool!

therefore, I would prefer an additional panel, like controlnet, in the middle of the webui, rather than an isolated tab.

**Comment by ototadana** [comment]
@dundund @figurehunt 
Added extension version.
You can install it from `https://github.com/ototadana/sd-face-editor.git`
Please try it out!

**Comment by figurehunt** [comment]
wow, it's cool. Thanks for your hard work! Will reinstall and test for it, cause these days are busy building rocket in Zelda ;)

**Comment by ototadana** [comment]
The readme has also been updated.
