### ISSUE TITLE
picture outside the face is affected

### ISSUE THREAD

**Issue by fanyangto** [ototadana/sd-face-editor#61]
When I use this face editor, the whole picture outside the face is affected (with added noises/elements).

The settings I used was:

1. img2img: CFG=7, denoise=0 (or 0.2 to minimize the change elsewhere)
2. face editor: mask margin 1.2, mask size 8, blur =0, denoise inside the mask 0.4, denoise for the rest 0
apply inside the mask checked.

After the processing, arms have a lot freckles, and the beach is dotted with a lot more white shell fragments.

Am I using it incorrectly ?

**Comment by ototadana** [comment]
@fanyangto 
If you do not want to change the original image as much as possible, try the following:
- Use the script instead of the extension. Please refer to the instructions [here](https://github.com/ototadana/sd-face-editor#fixing-images-that-already-exist).
- Set the value of  "Denoising strength for the entire image"  to 0.

**Comment by fanyangto** [comment]
OMG, I have been using extensions and scripts interchangeably, didn't notice I have been swing between the two, no longer I didn't get consistent results. Thank  you! I will give it a try and report back good news.  ;-)
